import {DEFAULT_ALPHA_NEUTRAL_CONFIG} from '@/lib/neutral-engine/alphaNeutralTokens'
import {buildArchitectureRamps, rampForTheme} from '@/lib/neutral-engine/architectureRamps'
import {
  DEFAULT_ADVANCED_DARK_SCALE,
  DEFAULT_ADVANCED_LIGHT_SCALE,
} from '@/lib/neutral-engine/defaultGlobalScaleConfig'
import {DEFAULT_SYSTEM_MAPPING} from '@/lib/neutral-engine/defaultSystemMapping'
import {applyContrastEmphasisToSystemMapping} from '@/lib/neutral-engine/effectiveMapping'
import {exportCssVariables} from '@/lib/neutral-engine/exportFormats'
import {clampSystemMappingToLadderLength, deriveSystemTokens} from '@/lib/neutral-engine/systemMap'

const ramps = buildArchitectureRamps({
  architecture: 'advanced',
  globalScale: DEFAULT_ADVANCED_LIGHT_SCALE,
  lightScale: DEFAULT_ADVANCED_LIGHT_SCALE,
  darkScale: DEFAULT_ADVANCED_DARK_SCALE,
})

const lightRamp = rampForTheme(ramps, 'light')
const darkRamp = rampForTheme(ramps, 'darkElevated')

const mappingLight = clampSystemMappingToLadderLength(lightRamp.length, DEFAULT_SYSTEM_MAPPING)
const mappingDark = clampSystemMappingToLadderLength(darkRamp.length, DEFAULT_SYSTEM_MAPPING)

const effectiveMappingLight = applyContrastEmphasisToSystemMapping(mappingLight, 'default')
const effectiveMappingDark = applyContrastEmphasisToSystemMapping(mappingDark, 'default')

const lightTokens = deriveSystemTokens(lightRamp, {...effectiveMappingLight, themeMode: 'light'})
const darkTokens = deriveSystemTokens(darkRamp, {...effectiveMappingDark, themeMode: 'darkElevated'})

const defaultCss = exportCssVariables({
  architecture: 'advanced',
  ramps,
  light: lightTokens,
  dark: darkTokens,
  alphaConfig: DEFAULT_ALPHA_NEUTRAL_CONFIG,
})

// Content is generated by exportCssVariables from internal defaults — not user input.
// dangerouslySetInnerHTML is required for inline <style> tags in React/Next.js.
export function DefaultThemeStyles() {
  // eslint-disable-next-line react/no-danger
  return <style id="ns-live-tokens" dangerouslySetInnerHTML={{__html: defaultCss}} />
}
